package com.asm.immoManager.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

@Entity
@Table(name = "users")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "name is required.")
    @Column(name = "name", nullable = false)
    private String name;

    @NotBlank(message = "Email is required.")
    @Email(message = "Email should be valid.")
    @Column(name = "email", nullable = false)
    private String email;

    @NotBlank(message = "phone is required.")
    @Column(name = "phone", nullable = false)
    private String phone = "add a phone number";

    @Column(name = "is_admin", nullable = false)
    private boolean admin;

    @NotBlank(message = "password is required.")
    @Column(name = "password", nullable = false)
    private String password;

    // getters and setters generated by Lombok
}
